version: '3.9'
services:
    roach1:
        container_name: roach1
        hostname: roach1
        image: cockroachdb/cockroach:v22.1.10
        expose:
            - '26257'
        ports:
            - '26257:26257'
            - '8080:8080'
        volumes:
            - ./certs/node1:/cockroach/certs:r
            - ./data/node1:/cockroach/cockroach-data
        networks:
            - roachnet
        command: start --join=roach1,roach2,roach3 --certs-dir=certs
        # command: start --logtostderr --join=roach1,roach2,roach3 --certs-dir=certs

    roach2:
        container_name: roach2
        hostname: roach2
        image: cockroachdb/cockroach:v22.1.10
        expose:
            - '26257'
        volumes:
            - ./certs/node2:/cockroach/certs:r
            - ./data/node2:/cockroach/cockroach-data
        networks:
            - roachnet
        command: start --join=roach1,roach2,roach3 --certs-dir=certs
        # command: start --logtostderr --join=roach1,roach2,roach3 --certs-dir=certs

    roach3:
        container_name: roach3
        hostname: roach3
        image: cockroachdb/cockroach:v22.1.10
        expose:
            - '26257'
        volumes:
            - ./certs/node3:/cockroach/certs:r
            - ./data/node3:/cockroach/cockroach-data
        networks:
            - roachnet
        command: start --join=roach1,roach2,roach3 --certs-dir=certs
        # command: start --logtostderr --join=roach1,roach2,roach3 --certs-dir=certs

networks:
    roachnet:
