version: '3.9'
services:
    app1:
        container_name: app1
        hostname: app1
        build: .
        expose:
            - '9090'
        environment:
            - DB_HOST_NAME=host.docker.internal
            - DB_PORT=9292
            - DB_NAME=defaultdb
            - DB_USER=root
            - DB_PWD=welcome123
            - APP_LISTEN_PORT=9090
            - APP_NAME=app_node_1
        networks:
            - appnet
        command: ./app
    app2:
        container_name: app2
        hostname: app2
        build: .
        expose:
            - '9090'
        environment:
            - DB_HOST_NAME=host.docker.internal
            - DB_PORT=9292
            - DB_NAME=defaultdb
            - DB_USER=root
            - DB_PWD=welcome123
            - APP_LISTEN_PORT=9090
            - APP_NAME=app_node_2
        networks:
            - appnet
        command: ./app
    app3:
        container_name: app3
        hostname: app3
        build: .
        expose:
            - '9090'
        environment:
            - DB_HOST_NAME=host.docker.internal
            - DB_PORT=9292
            - DB_NAME=defaultdb
            - DB_USER=root
            - DB_PWD=welcome123
            - APP_LISTEN_PORT=9090
            - APP_NAME=app_node_3
        networks:
            - appnet
        command: ./app

    app_lb:
        container_name: app_lb
        hostname: app_lb
        image: envoyproxy/envoy-dev:e0cc4306253f0318f9dcbc77cf32feb6245c378f
        ports:
            - '9191:9191'
        volumes:
            - ./envoy-app.yaml:/etc/envoy/envoy.yaml
        networks:
            - appnet
networks:
    appnet:
